import Foundation

// MARK: - MCPRuntime
//
// Deploys the DoomCoder MCP server to ~/.doomcoder/mcp.py on every app launch.
// The MCP server is a small Python 3 script that speaks JSON-RPC 2.0 over stdio
// (Model Context Protocol) and forwards `dc` tool calls onto the same
// ~/.doomcoder/dc.sock Unix socket the shell-hook runner uses.
//
// Why Python 3 and not a Swift binary?
//   • Zero Xcode-target surgery — we mirror HookRuntime's "generate + deploy"
//     strategy, which has been battle-tested in Phase A.
//   • /usr/bin/python3 is present on every supported macOS; the system stub
//     auto-installs Command Line Tools on first use if needed, and every user
//     of this app is by definition a developer with CLT already.
//   • The MCP protocol is trivial enough that a ~120-line script is faster to
//     reason about than pulling in a full SDK.
//
// On every launch we overwrite the script if the on-disk version stamp
// (DC_MCP_VERSION) doesn't match the current source version. That lets users
// pick up fixes simply by relaunching the app.

enum MCPRuntime {

    /// Bumped on every edit of `pythonSource`. Written as a comment stamp at
    /// the top of the deployed script so we know when to re-deploy.
    static let version: Int = 1

    static var directory: URL {
        FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".doomcoder", isDirectory: true)
    }

    static var scriptURL: URL {
        directory.appendingPathComponent("mcp.py")
    }

    /// The shell command every MCP config will point at. `python3` is
    /// resolved via the user's PATH, which on every modern macOS is
    /// `/usr/bin/python3`.
    static var invocation: (command: String, args: [String]) {
        ("/usr/bin/python3", [scriptURL.path])
    }

    /// Deploys (or refreshes) ~/.doomcoder/mcp.py. No-ops if the on-disk
    /// version stamp already matches the current source, so this is cheap
    /// to call on every launch.
    static func deploy() throws {
        let fm = FileManager.default
        try fm.createDirectory(at: directory, withIntermediateDirectories: true)

        if fm.fileExists(atPath: scriptURL.path),
           let existing = try? String(contentsOf: scriptURL, encoding: .utf8),
           existing.contains("DC_MCP_VERSION=\(version)") {
            return
        }

        try pythonSource.write(to: scriptURL, atomically: true, encoding: .utf8)

        // chmod 0755 so the user can invoke it directly if they want to debug;
        // MCP clients invoke via /usr/bin/python3 so we do not rely on +x.
        try fm.setAttributes([.posixPermissions: 0o755], ofItemAtPath: scriptURL.path)
    }

    /// True if the script exists on disk at the current version. Surfaced in
    /// the Settings UI so users can see at a glance whether a re-launch is
    /// needed to pick up a fix.
    static var isDeployed: Bool {
        guard let s = try? String(contentsOf: scriptURL, encoding: .utf8) else { return false }
        return s.contains("DC_MCP_VERSION=\(version)")
    }

    // MARK: - Script source

    private static let pythonSource: String = """
    #!/usr/bin/env python3
    # DoomCoder MCP server — DC_MCP_VERSION=\(version)
    # Generated by DoomCoder. Overwritten on every app launch when the version
    # stamp above doesn't match. Do not edit by hand.
    #
    # Speaks MCP (Model Context Protocol) over stdio, exposing a single tool
    # named `dc` that forwards an AgentEvent onto ~/.doomcoder/dc.sock.
    import json, os, socket, sys, time

    SOCK = os.path.expanduser("~/.doomcoder/dc.sock")

    def _send(obj):
        sys.stdout.write(json.dumps(obj, separators=(",",":")) + "\\n")
        sys.stdout.flush()

    def _reply(rid, result=None, error=None):
        msg = {"jsonrpc": "2.0", "id": rid}
        if error is not None:
            msg["error"] = error
        else:
            msg["result"] = result
        _send(msg)

    def _forward(args):
        evt = {
            "agent":  str(args.get("agent", "unknown"))[:64],
            "status": str(args.get("status", "i"))[:1],
            "source": "mcp",
            "ts":     int(time.time()),
        }
        for k in ("message", "tool", "cwd", "sessionKey", "repo"):
            if args.get(k) is not None:
                evt[k] = str(args[k])[:512]
        try:
            s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
            s.settimeout(0.5)
            s.connect(SOCK)
            s.sendall((json.dumps(evt) + "\\n").encode("utf-8"))
            s.close()
            return True, ""
        except OSError as e:
            return False, str(e)

    _TOOLS = [{
        "name": "dc",
        "description": (
            "Notify DoomCoder that this AI agent changed state. Call whenever "
            "you start or finish work, or are waiting for the user. Pass the "
            "agent id (e.g. 'cursor', 'windsurf', 'gemini-cli') and a one-char "
            "status: 's' start, 'w' waiting-for-input, 'i' info/progress, "
            "'e' error, 'd' done."
        ),
        "inputSchema": {
            "type": "object",
            "properties": {
                "agent":      {"type": "string"},
                "status":     {"type": "string", "enum": ["s","w","i","e","d"]},
                "message":    {"type": "string"},
                "tool":       {"type": "string"},
                "cwd":        {"type": "string"},
                "sessionKey": {"type": "string"},
                "repo":       {"type": "string"}
            },
            "required": ["agent", "status"]
        }
    }]

    def _handle(msg):
        method = msg.get("method")
        rid = msg.get("id")
        if method == "initialize":
            _reply(rid, result={
                "protocolVersion": "2024-11-05",
                "capabilities": {"tools": {"listChanged": False}},
                "serverInfo": {"name": "doomcoder", "version": "\(version).0.0"}
            })
        elif method == "tools/list":
            _reply(rid, result={"tools": _TOOLS})
        elif method == "tools/call":
            p = msg.get("params", {})
            if p.get("name") != "dc":
                _reply(rid, error={"code": -32602, "message": "unknown tool"})
                return
            ok, err = _forward(p.get("arguments", {}))
            text = "ok" if ok else ("doomcoder not running: " + err)
            _reply(rid, result={"content": [{"type": "text", "text": text}], "isError": not ok})
        elif method in ("notifications/initialized", "notifications/cancelled", "ping"):
            if rid is not None:
                _reply(rid, result={})
        else:
            if rid is not None:
                _reply(rid, error={"code": -32601, "message": "method not found: " + str(method)})

    def main():
        for line in sys.stdin:
            line = line.strip()
            if not line:
                continue
            try:
                msg = json.loads(line)
            except json.JSONDecodeError:
                continue
            try:
                _handle(msg)
            except Exception as e:
                rid = msg.get("id") if isinstance(msg, dict) else None
                if rid is not None:
                    _reply(rid, error={"code": -32603, "message": str(e)[:200]})

    if __name__ == "__main__":
        main()
    """
}
