// OpenCodePluginTemplate.swift — Doom Coder (Mac)
//
// opencode is the one tracked agent with no shell-command config hook. Instead
// it loads in-process JS/TS plugins from ~/.config/opencode/plugin/*.{ts,js}
// (for BOTH the CLI/TUI and the desktop app). We therefore install a tiny
// plain-JS plugin that forwards a curated set of opencode lifecycle events to
// the existing `dc-hook` helper, which relays them to Doom Coder over the unix
// socket — exactly the same ingestion contract as every other agent, and zero
// LLM tokens.
//
// Design constraints baked into the generated file (verified against
// opencode-dev, June 2026):
//   • Plain `.js`, not `.ts` — the desktop app's runtime may be Node, which
//     can't transpile TS on the fly. `.js` loads everywhere.
//   • Exactly ONE export, and it's a function — opencode's legacy plugin loader
//     (`getLegacyPlugins`) throws if any module export is not a function.
//   • Uses `node:child_process`, never opencode's injected Bun `$` (which is
//     `undefined` outside Bun).
//   • Every code path swallows errors so a misbehaving socket can never disrupt
//     an opencode session.
//   • The `event` hook is the catch-all bus subscription; tool.execute.before/
//     after are dedicated trigger hooks. High-frequency events are filtered out
//     in-process so we only spawn dc-hook for meaningful lifecycle events.

import Foundation

enum OpenCodePluginTemplate {

    /// Renders the plugin source with the absolute dc-hook path baked in.
    /// The path is JSON-encoded so spaces / unusual characters in
    /// "Application Support" are safe inside the JS string literal.
    static func render(dcHookPath: String) -> String {
        let encodedPath = jsonString(dcHookPath)
        return """
        // doomcoder:dc-hook agent=opencode — MANAGED FILE, DO NOT EDIT.
        // Auto-generated by the Doom Coder macOS app. Forwards opencode lifecycle
        // events to the dc-hook helper (zero LLM tokens). Reinstalling Doom Coder
        // hooks overwrites this file; deleting it disables opencode tracking.

        const DC_HOOK = \(encodedPath)

        // Curated allow-list. Everything else (streaming text/reasoning deltas,
        // file-watcher noise, etc.) is dropped in-process so we never spawn a
        // helper for high-frequency events.
        //
        // "agent is blocked waiting on you" is EXACTLY permission.asked +
        // question.asked (opencode's own blocker logic uses this same pair).
        // question.asked is opencode's elicitation / multiple-choice / needs-
        // input mechanism — it does NOT have a dedicated trigger hook, so the
        // event bus is the only way to observe it.
        const FORWARD = new Set([
          "session.created",
          "session.idle",
          "session.error",
          "session.compacted",
          "session.deleted",
          "permission.asked",
          "permission.replied",
          "question.asked",
          "question.replied",
          "question.rejected",
          "file.edited",
        ])

        let _spawn = undefined
        async function getSpawn() {
          if (_spawn !== undefined) return _spawn
          try {
            const cp = await import("node:child_process")
            _spawn = cp.spawn
          } catch (_e1) {
            try {
              const cp = await import("child_process")
              _spawn = cp.spawn
            } catch (_e2) {
              _spawn = null
            }
          }
          return _spawn
        }

        async function forward(type, payload) {
          try {
            const spawn = await getSpawn()
            if (!spawn) return
            const child = spawn(DC_HOOK, ["opencode", type], {
              stdio: ["pipe", "ignore", "ignore"],
            })
            child.on("error", () => {})
            try {
              child.stdin.on("error", () => {})
              child.stdin.write(JSON.stringify(payload || {}))
              child.stdin.end()
            } catch (_e) {}
            if (typeof child.unref === "function") child.unref()
          } catch (_e) {}
        }

        // Single function export (opencode legacy plugin contract).
        export const DoomCoderPlugin = async (input) => {
          const directory = (input && input.directory) || undefined
          return {
            async event({ event }) {
              try {
                if (!event || !FORWARD.has(event.type)) return
                const props =
                  event.properties && typeof event.properties === "object"
                    ? event.properties
                    : {}
                await forward(event.type, Object.assign({}, props, { directory }))
              } catch (_e) {}
            },
            async "tool.execute.before"(toolInput) {
              try {
                await forward("tool.execute.before", {
                  sessionID: toolInput && toolInput.sessionID,
                  tool: toolInput && toolInput.tool,
                  callID: toolInput && toolInput.callID,
                  directory,
                })
              } catch (_e) {}
            },
            async "tool.execute.after"(toolInput, toolOutput) {
              try {
                await forward("tool.execute.after", {
                  sessionID: toolInput && toolInput.sessionID,
                  tool: toolInput && toolInput.tool,
                  callID: toolInput && toolInput.callID,
                  title: toolOutput && toolOutput.title,
                  directory,
                })
              } catch (_e) {}
            },
          }
        }
        """
    }

    /// Minimal JSON string encoder for a single value, used to embed an
    /// absolute path as a safely-escaped JS string literal.
    private static func jsonString(_ s: String) -> String {
        if let data = try? JSONSerialization.data(withJSONObject: [s], options: []),
           let arr = String(data: data, encoding: .utf8) {
            // arr == ["...escaped..."] — strip the surrounding brackets.
            return String(arr.dropFirst().dropLast())
        }
        // Fallback: manual escape of the two characters that matter in a path.
        let escaped = s.replacingOccurrences(of: "\\", with: "\\\\")
                       .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }
}
